### PR TITLE
fix: add limit on bookmarks shown

### LINKED ISSUE #877: Limit number of bookmarks shown on home
We should limit the number of bookmarks shown on home, so it does not take the whole view. 

Also propose a way to see all your bookmarks in a single page.

### PR DESCRIPTION
**Pull request by spaenleh**
close #877

### CODE REVIEW

File: src/modules/home/bookmarks/ItemFavoriteCard.tsx [hunk 1]
```diff
@@ -19,7 +19,7 @@ type Props = {
   item: PackedItem;
 };
 
-export function ItemCard({ item }: Readonly<Props>): JSX.Element {
+export function ItemFavoriteCard({ item }: Readonly<Props>): JSX.Element {
```
Comment (pyphilia) [inline src/modules/home/bookmarks/ItemFavoriteCard.tsx:22]:
```suggestion
export function BookmarkCard({ item }: Readonly<Props>): JSX.Element {
```

**Review by pyphilia — APPROVED** [review]
Great! I just suggested to rename a component^^
